# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import gitos.enums
import gitos.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gitos', '0003_auto_20180325_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubIssueBounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('amount', gitos.fields.MoneyField(decimal_places=18, max_digits=28)),
                ('status', enumfields.fields.EnumField(enum=gitos.enums.GithubIssueBountyStatus, max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitos.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
