# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitos', '0005_remove_githubissuebounty_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubissuebounty',
            name='issue_nr',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
